### ISSUE TITLE
true_divide renamed to divide in NumPy>=1.23

### ISSUE THREAD

**Issue by kbrix2000** [PTNobel/AutoDiff#2]
Starting from NumPy 1.23, it seems that the function `np.true_divide()` has been renamed to `np.divide()` and the decorator `register` fails in [line 364 of `vecvalder_funcs_and_ufuncs.py`](https://github.com/PTNobel/AutoDiff/blob/caed5e47a408e8668394d3aeabf5db7900551895/auto_diff/vecvalder_funcs_and_ufuncs.py#L364).

As a workaround, it helps to rename  `true_divide` to `divide` also in `vecvalder_funcs_and_ufuncs.py`. But obviously, it would be better to have a switch here depending on the NumPy version number.

**Comment by PTNobel** [comment]
Thanks for the heads up! Any chance you know where in the changelog this change is discussed?

I'm happy to support old NumPy versions for a few years, but want to make sure I know exactly which version changed.

**Comment by prxq2** [comment]
I can reproduce this problem with Python 3.8 or later compiled from sources with default options, installing in a corresponding virtual environment auto_diff either via pip or by cloning this repo. Just importing the library leads to the problem.

The second `assert` in `vecvalder.register`
```
def register(np_fn,  override_name_check = False):
    assert np_fn not in _HANDLED_FUNCS_AND_UFUNCS

    def decorator(f):
        assert np_fn.__name__ == f.__name__  # this one fails when doing register(np.true_divide)
        _HANDLED_FUNCS_AND_UFUNCS[np_fn] = f
        return f
    return decorator
```
is triggered because, alas, `np.true_divide.__name__` is actually `"divide"`.

The issue is weird because I've used pip installed versions of this library in Winpython with python 3.8 and 3.9. and there the assertion was not triggered. Thus I thought at first also that this was a change in numpy, because it broke on a new installation.

I think the easiest solution is to simply remove the assertion in vecvalder.register as well as in sparsevecvalder.register. Auto_diff works 100% correctly without it, but the assertion fails for what seem to be esoteric reasons related with naming and aliasing in numpy.

**Comment by PTNobel** [comment]
Hmmm the assertion was *very* useful when I was building this library to catch many typoes, but since the library is basically in maintenance mode I guess we can remove it now.
